/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeadBar: typeof import('./src/components/bar/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconEmailFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconEmailFill']
    IconSearchOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSearchOutline']
    Menu: typeof import('./src/components/bar/Menu.vue')['default']
    MenuBar: typeof import('./src/components/bar/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopTitle: typeof import('./src/components/bar/TopTitle.vue')['default']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkColorPicker: typeof import('@yike-design/ui')['YkColorPicker']
    YkInput: typeof import('@yike-design/ui')['YkInput']
    YkInputSearch: typeof import('@yike-design/ui')['YkInputSearch']
    YkPagination: typeof import('@yike-design/ui')['YkPagination']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
    YkTitle: typeof import('@yike-design/ui')['YkTitle']
  }
}
